# Generated by Django 5.2.1 on 2025-05-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('prize', models.CharField(max_length=128)),
            ],
        ),
    ]
