# Generated by Django 5.2.1 on 2025-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signup_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
            ],
        ),
    ]
