# Generated by Django 5.1.6 on 2025-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recent_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
