# Generated by Django 5.1.6 on 2025-05-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reportupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_title', models.CharField(max_length=128)),
                ('feedback_content', models.CharField(max_length=1280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
