# Generated by Django 5.1.6 on 2025-05-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
