# Generated by Django 5.1.6 on 2025-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportupload',
            name='username',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportupload',
            name='description',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reportupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
