# Generated by Django 5.1.6 on 2025-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reportupload_username_alter_reportupload_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportupload',
            name='uploaded_at',
            field=models.DateTimeField(max_length=128),
        ),
    ]
